version: "3.9"
services:
  exam:
    build: ../ExamService
    ports:
      - "8050:8080"
  schoolgateway:
    build: .
    ports:
      - "8060:8080"
  student:
    build: ../StudentService
    ports:
      - "8070:8080"

  teacher:
    build: ../TeacherService
    ports:
      - "8040:8080"

#  eureka:
#    build: ../DiscoveryServer
#    ports:
#      - "8761:8762"
  postgres:
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=school
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432