DROP TABLE IF EXISTS TEACHER;

CREATE TABLE TEACHER(
    sid LONG AUTO_INCREMENT PRIMARY KEY,
    firstname VARCHAR(20) NOT NULL,
    lastname VARCHAR(20) NOT NULL,
    course ENUM ('TEST', 'DLS', 'SI')
);