DROP TABLE IF EXISTS STUDENT;

CREATE TABLE STUDENT(
    sid INT PRIMARY KEY,
    name VARCHAR(25) NOT NULL,
    email VARCHAR(25) NOT NULL,
    gender ENUM ('FEMALE', 'MALE'),
    semester ENUM('SEM1', 'SEM2', 'SEM3'),
    si ENUM ('PASSED', 'NOTPASSED') DEFAULT 'NOTPASSED',
    test ENUM ('PASSED', 'NOTPASSED') DEFAULT 'NOTPASSED',
    dls ENUM ('PASSED', 'NOTPASSED') DEFAULT 'NOTPASSED'
);