DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE(
    employee_id LONG AUTO_INCREMENT PRIMARY KEY,
    firstname VARCHAR(20) NOT NULL,
    lastname VARCHAR(20) NOT NULL,
    subject VARCHAR(20) NOT NULL
);
CREATE TABLE STUDENT(
    sid LONG AUTO_INCREMENT PRIMARY KEY,
    sname VARCHAR(25) NOT NULL,
    smail VARCHAR(25) NOT NULL
);