        version: "3.9"
        services:
          eurekaserv:
            build: .
            ports:
              - "8761:8761"
          exam:
            build: ../ExamService
            ports:
              - "8060:8060"
            environment:
              EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserv:8761/eureka
            links:
              - eurekaserv
          student:
            build: ../StudentService
            ports:
              - "8070:8070"
            environment:
              EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserv:8761/eureka
            links:
              - eurekaserv
          teacher:
            build: ../TeacherService
            ports:
              - "8090:8090"
            environment:
              EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserv:8761/eureka
            links:
              - eurekaserv
          postgres:
            image: postgres:13.1
            healthcheck:
              test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
              timeout: 45s
              interval: 10s
              retries: 10
            restart: always
            environment:
              - POSTGRES_USER=root
              - POSTGRES_PASSWORD=1234
              - APP_DB_USER=docker
              - APP_DB_PASS=docker
              - APP_DB_NAME=school
            volumes:
              - ./db:/docker-entrypoint-initdb.d/
            ports:
              - 5432:5432